### PR TITLE
Feature/pipelines

### PR DESCRIPTION
**Pull request by defunctl**
### TODO
- [ ] create `moderntribe/square1-pipeline` repo before release.

A remake/standalone version of https://github.com/illuminate/pipeline for square one that adds PHP-DI support and the ability to pass additional parameters to each stage besides the `$passable` and `$next` variables.

image

[image source](https://dev.to/abrardev99/pipeline-pattern-in-laravel-278p)

Pasting in the README from this PR:

# Pipeline

This is a customized implementation of Laravel's [illuminate/pipeline](https://github.com/illuminate/pipeline) to work with PHP-DI and to allow passing additional parameters to your stages.

This library implements a version of the [Collection Pipeline Design Pattern](https://martinfowler.com/articles/collection-pipeline/) and the [Chain of Responsibility Design Pattern](https://refactoring.guru/design-patterns/chain-of-responsibility). 

This system is what powers [Laravel's Middleware](https://laravel.com/docs/8.x/middleware) under the hood and is very useful if you want to run multiple operations in a sequence on the same data set.

Each stage can perform a specific operation, or decide to skip that operation based on some condition and pass the data to the next stage in line.

See the [integration tests](https://github.com/moderntribe/tribe-libs/blob/b49d9d659b0458ec46ecf1ae96329799d502506c/tests/integration/Tribe/Libs/Pipeline/PipelineTest.php) for some basic example use cases.

## Example Use Cases

1. As request/response middleware or any middleware.
2. As a filter/facet system, e.g. building a query based on a number of selectable parameters: sort/order, post status, date etc...
3. As an access control system, allowing access by role or a number of different conditions.
4. As a formatting/transforming/data mapping system.
5. As a sanitizing system, performing different sanitization techniques based on the structure of the data.

### CODE REVIEW

**Review by ChrisMKindred — APPROVED** [review]
This all looks good, I especially appreciate the tests which helped me follow the use case a little better. Are you using this in a project already?  I would be interested in seeing the full implementation.

**Comment by defunctl** [comment]
> This all looks good, I especially appreciate the tests which helped me follow the use case a little better. Are you using this in a project already? I would be interested in seeing the full implementation.

Sure am! It's a work in progress though, but here's a snapshot with the general idea:

1. [Pipeline stages being registered](https://github.com/moderntribe/explore-navigation/blob/257e325646f62b925d458ae5cd8e81f3714bc7ed/src/Serializers/Serializer_Definer.php)
2. [The class that processes the pipeline](https://github.com/moderntribe/explore-navigation/blob/257e325646f62b925d458ae5cd8e81f3714bc7ed/src/Serializers/Field_Serializer.php)
3. [Each stage that maps a post into a schema format for Azure Cognitive Search](https://github.com/moderntribe/explore-navigation/tree/257e325646f62b925d458ae5cd8e81f3714bc7ed/src/Serializers/Stages)

**Review by nickpelton — APPROVED** [review]
This is a really nice and powerful pattern to provide folks. I would be curious how we could implement this in combination with a filter, so we could inject additional handlers in some situations. Really neat. Thanks Justin!

**Comment by defunctl** [comment]
> This is a really nice and powerful pattern to provide folks. I would be curious how we could implement this in combination with a filter, so we could inject additional handlers in some situations. Really neat. Thanks Justin!

Check out the example in Explore Navigation: https://github.com/moderntribe/explore-navigation/blob/257e325646f62b925d458ae5cd8e81f3714bc7ed/src/Serializers/Serializer_Definer.php

A developer could just create their own definer and place the stages however they want. As long as you build your processing class correctly (accepting an array of stages, and not building them in the class (open/closed principle), developers can use `DI\add()` to add to the list in their own definer, like how we do it with our WP-CLI commands right now.

There's also nothing stopping the developer from opening up the list via a filter, while not for the pipeline, the same logic applies here where I allow developers to modify the field definitions in my Definer, before they're ready to be used:  https://github.com/moderntribe/explore-navigation/blob/257e325646f62b925d458ae5cd8e81f3714bc7ed/src/Schema/Schema_Definer.php#L38

**Pull request merged**
