### PR TITLE
Feature: block middleware

### PR DESCRIPTION
**Pull request by defunctl**
Companion PR for https://github.com/moderntribe/square-one/pull/1014

## Changes
- Added: `wp s1 generate block:middleware <name>` CLI command to create sample block middleware.
- Added: `wp s1 generate block <name> --with-middleware` that adds the appropriate interface and a stub middleware parameters method to a generated block config.
- Updated: Block model generator template `model.php.tmpl` will use a different method name depending on if block middleware is detected in the version of Square One this library is included in.
- Added: `With_Field_Finder` trait, that can search a block object's fields for a specific field key.

## TODO
- [x] Add block middleware generators
- [x] Update `wp s1 generate block` to include a `--with-middleware` option and use the correct interface/params method
- [x] Update changelog

### CODE REVIEW

**Comment by defunctl** [comment]
Would love to hear everyone's thoughts on also automatically generating working integration tests automatically when the `wp s1 generate block:middleware <name>` command is run, which generates an actual working Field & Model middleware example.

Automatically creating tests alongside the sample middleware will force developers to look at them, and either:
- Willingly delete them.
- Or, ideally, customize them to their custom block middleware's functionality.

**Comment by ChrisMKindred** [comment]
> Would love to hear everyone's thoughts on also automatically generating working integration tests when the `wp s1 generate block:middleware <name>` command is run, which generates an actual working Field & Model middleware example.
> 
> Automatically creating tests alongside the sample middleware will force developers to look at them, and either:
> 
> * Willingly delete them.
> * Or, ideally, customize them to their custom block middleware's functionality.

@defunctl 

Anything we can do to make writing tests easier/quicker on the development team we should do. We should generate the test when we generate the middleware and mark it as incomplete by default. That way it isn't required by CI to pass, and there isn't any additional requirement by the developer if the choice is made that the middleware doesn't need tests. This also shines a light on the fact that tests really should be written when we can by including an `I` in the test reports.

Something like:
```php

...

final class SomethingMiddlewareTest extends WPTestCase {
        
        ... // Setup any extra stuff that is needed to test a middleware

	public function test_something_middleware(): void {

                 $this-> markTestIncomplete( 'Does the Something Middleware need a test?' );

	}
        
        ...

}
```

**Comment by defunctl** [comment]
@ChrisMKindred I've added some tests for the sample/example middleware.

Because this generator actually generates a real working middleware example, the tests generated reflect that as well and actually really test the example!

I think just having empty stub test methods isn't going to help teach anyone who isn't sure where to get started with tests, this way they actually have a real working test to adjust based on the changes they make to their middleware.

If you want to give it a test, checkout the branch in `square-one` in this PR which is using this branch in composer: https://github.com/moderntribe/square-one/pull/1014

And then:

```bash
so composer install
```

```bash
so wp s1 generate block:middleware Inject_Css
```

```bash
so test run integration Tribe/Project/Blocks/Middleware/Inject_Css
```
---

```bash
$so wp s1 generate block:middleware Inject_Css
Writing block field middleware file to /application/www/wp-content/plugins/core/src/Blocks/Middleware/Inject_Css/Field_Middleware/Inject_Css_Field_Middleware.php
Writing block field middleware test file to /application/www/dev/tests/tests/integration/Tribe/Project/Blocks/Middleware/Inject_Css/Field_Middleware/Inject_Css_Field_Middleware_Test.php
Writing model field middleware file to /application/www/wp-content/plugins/core/src/Blocks/Middleware/Inject_Css/Model_Middleware/Inject_Css_Model_Middleware.php
Writing model field middleware test file to /application/www/dev/tests/tests/integration/Tribe/Project/Blocks/Middleware/Inject_Css/Model_Middleware/Inject_Css_Model_Middleware_Test.php
Registering block middleware in Block_Middleware_Definer.php 
Success: Way to go! Inject_Css block middleware has been created
```
```bash
$ so test run integration Tribe/Project/Blocks/Middleware/Inject_Css
Cleaning up output /application/www/dev/tests/tests/_output/...
Done
Codeception PHP Testing Framework v4.2.1 https://helpukrainewin.org
Powered by PHPUnit 9.4.4 by Sebastian Bergmann and contributors.

Integration Tests (2) ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✔ Inject_Css_Field_Middleware_Test: Test_it_injects_css_section_and_field_into_a_block (0.01s)
✔ Inject_Css_Model_Middleware_Test: Test_it_merges_css_class_into_model_data (0.02s)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 00:00.903, Memory: 50.50 MB

OK (2 tests, 7 assertions)
```

**Review by ChrisMKindred — APPROVED** [review]
Looks Good!

**Pull request merged**
